---
- name: "Create RDS instance"
  hosts: localhost
  vars: 
    allocated_storage: 10 
    DB_ENGINE: "mariadb"
    DB_ID: "CFI-validator-db"
    DB_AWS_REGION: "us-east-2"
  
    
  tasks:
  - name: Create a new DB instance in RDS/AWS in the default VPC
    community.aws.rds_instance:
      aws_region: "{{ DB_AWS_REGION }}"
      id: "{{ DB_ID }}"
      state: present
      engine: "{{ DB_ENGINE }}"
      storage_encrypted: True
      db_instance_class: db.t2.medium
      allocated_storage: "{{ allocated_storage }}"
      master_username: "{{ master_username }}"
      master_user_password: "{{ master_user_password }}"

    register: dbdetails

  - name: Print the details of the database
    debug:
      var: dbdetails

