#########################################################
##                                                     ##
##                  CREATE SERVICE                     ##
##                                                     ##
#########################################################

name: deploy_validate_destroy_rds

on:
  push:
    branches:
      - dev  # Adjust this to your main branch name

env:
  WRITEDIRECTORY: '~/privateer_output'
  CONFIG: '~/privateer/privateer/example-config.yaml'
  DESTROY: true

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Use the desired Python version

    - name: Install Ansible and botocore
      run: |
        python -m pip install --upgrade pip
        pip install ansible
        pip install boto3 botocore

    - name: Run Ansible playbook
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
        MASTER_USERNAME: ${{ secrets.MASTER_USERNAME}}
        MASTER_USER_PASSWORD: ${{ secrets.MASTER_USER_PASSWORD}}
      
      run: ansible-playbook -e "aws_access_key=$AWS_ACCESS_KEY_ID aws_secret_key=$AWS_SECRET_ACCESS_KEY master_username=$MASTER_USERNAME master_user_password=$MASTER_USER_PASSWORD" ansible/create-rds-db.yaml
      
  
#########################################################
##                                                     ##
##                VALIDATE SERVICE                     ##
##                                                     ##
#########################################################


  validate:
    name: validate
    needs: deploy
    runs-on: ubuntu-latest
    continue-on-error: true

    # We don't currently have a working installer for privateer and its raids, so building from source for now
    # TODO: get config from GitHub Secrets
    # TODO: save output as artifacts
    steps:
      - name: Fetch and Build Privateer
        run: |
          git clone --branch v0.0.1 --depth 1 https://github.com/privateerproj/privateer privateer
          cd privateer
          go build
      
      - name: Fetch and Build RDS Raid
        run: |
          git clone --branch v0.0.2 --depth 1 https://github.com/krumIO/raid-rds
          cd raid-rds
          go build
          mkdir -p ~/privateer/bin
          mv raid-rds ~/privateer/bin/rds
        working-directory: ${{ github.workspace }}

      - name: Run privateer with an empty config, expecting failure
        run: ./privateer/privateer sally rds
        working-directory: ${{ github.workspace }}

      - name: Archive validation results
        uses: actions/upload-artifact@v3
        with:
          name: privateer-output
          path: ${{ env.WriteDirectory }}


#########################################################
##                                                     ##
##                  DESTROY SERVICE                    ##
##                                                     ##
#########################################################

  destroy:
    name: destroy
    needs: validate
    runs-on: ubuntu-latest
    if: ${{ env.DESTROY == 'true' }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Use the desired Python version

      - name: Install Ansible and botocore
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          pip install boto3 botocore

      - name: Run Ansible playbook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}

        run: ansible-playbook -e "aws_access_key=$AWS_ACCESS_KEY_ID aws_secret_key=$AWS_SECRET_ACCESS_KEY" ansible/delete-rds-db.yaml
